# -*- coding: utf-8 -*-
"""Normal_Distribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0Xzpx0NtHYYdL928ZbMnjwfEcbMZ-mw
"""

def estimate_gaussian_parameters(data):
    # Compute mean
    n = len(data)
    mean = sum(data) / n

    # Compute variance
    variance = sum((x - mean) ** 2 for x in data) / n

    return mean, variance

# Function to read data from a file
def read_data_from_file(filename):
    with open(filename, 'r') as file:
        data = [float(line.strip()) for line in file]
    return data

# Read data from files
dataset1 = read_data_from_file("AvgMaleHeight.txt")
dataset2 = read_data_from_file("DailyRainfall.txt")
dataset3 = read_data_from_file("WeeklyExpenditures.txt")

# Estimate parameters
mu1, sigma_sq1 = estimate_gaussian_parameters(dataset1)
mu2, sigma_sq2 = estimate_gaussian_parameters(dataset2)
mu3, sigma_sq3 = estimate_gaussian_parameters(dataset3)

# Print results
print(f"AvgMaleHeight: Mean = {mu1}, Variance = {sigma_sq1}")
print(f"DailyRainfall: Mean = {mu2}, Variance = {sigma_sq2}")
print(f"WeeklyExpenditures: Mean = {mu3}, Variance = {sigma_sq3}")